// Demo anime database (comprehensive dataset for testing)
const DEMO_ANIME_DATABASE = [
    {
        id: 1,
        title: "Overlord",
        titleSecondary: "Overlord",
        genres: ["Action", "Adventure", "Fantasy", "Supernatural"],
        tags: ["Magic", "Medieval", "Isekai", "Dark Fantasy", "Undead", "Kingdom Building", "Overpowered Protagonist", "Evil Protagonist"],
        description: "A powerful wizard finds himself trapped in a game world as an undead overlord, commanding loyal NPCs while exploring this new reality and building his dominion.",
        image: "https://cdn.myanimelist.net/images/anime/3/72653.jpg",
        score: 7.8,
        episodes: 39,
        status: "Finished",
        year: 2015,
        type: "TV",
        studio: "Madhouse"
    },
    {
        id: 2,
        title: "KonoSuba: God's Blessing on This Wonderful World!",
        titleSecondary: "Kono Subarashii Sekai ni Shukufuku wo!",
        genres: ["Adventure", "Comedy", "Fantasy", "Supernatural"],
        tags: ["Isekai", "Magic", "Comedy", "Friendship", "Parody", "Adventure", "Medieval", "Goddess", "Party", "Explosion"],
        description: "A boy is transported to a fantasy world with a useless goddess and must defeat the demon king while dealing with his dysfunctional party members.",
        image: "https://cdn.myanimelist.net/images/anime/8/77831.jpg",
        score: 8.2,
        episodes: 30,
        status: "Finished",
        year: 2016,
        type: "TV",
        studio: "Studio Deen"
    },
    {
        id: 3,
        title: "Re:Zero - Starting Life in Another World",
        titleSecondary: "Re:Zero kara Hajimeru Isekai Seikatsu",
        genres: ["Drama", "Fantasy", "Psychological", "Thriller"],
        tags: ["Isekai", "Magic", "Time Loop", "Medieval", "Dark", "Psychological", "Death", "Suffering", "Mystery", "Witch"],
        description: "A boy is transported to a fantasy world where he discovers he can return to life after death, but must relive traumatic events to save those he cares about.",
        image: "https://cdn.myanimelist.net/images/anime/11/79410.jpg",
        score: 8.3,
        episodes: 50,
        status: "Finished",
        year: 2016,
        type: "TV",
        studio: "White Fox"
    },
    {
        id: 4,
        title: "Attack on Titan",
        titleSecondary: "Shingeki no Kyojin",
        genres: ["Action", "Drama", "Horror", "Supernatural"],
        tags: ["Military", "Dark", "Gore", "Survival", "Mystery", "Titans", "Medieval", "Bloody", "Violence", "Post-Apocalyptic"],
        description: "Humanity lives behind walls to protect themselves from giant humanoid Titans, but when the walls are breached, a young soldier vows to eliminate all Titans.",
        image: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
        score: 9.0,
        episodes: 75,
        status: "Finished",
        year: 2013,
        type: "TV",
        studio: "Wit Studio"
    },
    {
        id: 5,
        title: "Demon Slayer",
        titleSecondary: "Kimetsu no Yaiba",
        genres: ["Action", "Historical", "Supernatural"],
        tags: ["Demons", "Sword Fighting", "Family", "Friendship", "Historical", "Dark", "Shonen", "Brother Sister", "Training"],
        description: "A young boy becomes a demon slayer to save his sister who has been turned into a demon, while fighting against powerful demons that threaten humanity.",
        image: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
        score: 8.7,
        episodes: 32,
        status: "Finished",
        year: 2019,
        type: "TV",
        studio: "ufotable"
    },
    {
        id: 6,
        title: "Vampire Knight",
        titleSecondary: "Vampire Knight",
        genres: ["Drama", "Romance", "Supernatural", "Vampire"],
        tags: ["Vampire", "Blood", "Romance", "School", "Dark", "Gothic", "Love Triangle", "Shoujo", "Mysterious"],
        description: "A girl attends a boarding school where vampires and humans coexist, but dark secrets and forbidden love complicate her world.",
        image: "https://cdn.myanimelist.net/images/anime/10/14852.jpg",
        score: 6.8,
        episodes: 26,
        status: "Finished",
        year: 2008,
        type: "TV",
        studio: "Studio Deen"
    },
    {
        id: 7,
        title: "Hellsing Ultimate",
        titleSecondary: "Hellsing Ultimate",
        genres: ["Action", "Horror", "Supernatural", "Vampire"],
        tags: ["Vampire", "Blood", "Gore", "Dark", "Violence", "Anti-Hero", "Bloody", "Guns", "Nazi", "Horror"],
        description: "The Hellsing Organization fights supernatural threats with the help of Alucard, a powerful vampire, in this dark and bloody series.",
        image: "https://cdn.myanimelist.net/images/anime/3/40897.jpg",
        score: 8.4,
        episodes: 10,
        status: "Finished",
        year: 2006,
        type: "OVA",
        studio: "Satelight"
    },
    {
        id: 8,
        title: "Seraph of the End",
        titleSecondary: "Owari no Seraph",
        genres: ["Action", "Drama", "Supernatural", "Vampire"],
        tags: ["Vampire", "Military", "Apocalypse", "Friendship", "Dark", "Revenge", "Blood", "Post-Apocalyptic", "Shonen"],
        description: "After a virus kills all adults, vampires emerge to rule over the remaining children, but some humans fight back for freedom and revenge.",
        image: "https://cdn.myanimelist.net/images/anime/5/71909.jpg",
        score: 7.4,
        episodes: 24,
        status: "Finished",
        year: 2015,
        type: "TV",
        studio: "Wit Studio"
    },
    {
        id: 9,
        title: "My Hero Academia",
        titleSecondary: "Boku no Hero Academia",
        genres: ["Action", "School", "Shounen", "Superhero"],
        tags: ["School", "Superhero", "Friendship", "Training", "Competition", "Powers", "Hero", "Coming of Age", "Shonen"],
        description: "In a world where most people have superpowers, a powerless boy enrolls in a prestigious hero academy to become the greatest hero.",
        image: "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
        score: 8.5,
        episodes: 138,
        status: "Ongoing",
        year: 2016,
        type: "TV",
        studio: "Bones"
    },
    {
        id: 10,
        title: "Toradora!",
        titleSecondary: "Toradora!",
        genres: ["Comedy", "Drama", "Romance", "School"],
        tags: ["School", "Romance", "Comedy", "Love Triangle", "Slice of Life", "Tsundere", "High School", "Coming of Age"],
        description: "A gentle guy with scary eyes and a small but fierce girl help each other pursue their respective crushes, but end up falling for each other.",
        image: "https://cdn.myanimelist.net/images/anime/13/22128.jpg",
        score: 8.1,
        episodes: 25,
        status: "Finished",
        year: 2008,
        type: "TV",
        studio: "J.C.Staff"
    },
    {
        id: 11,
        title: "Neon Genesis Evangelion",
        titleSecondary: "Shinseiki Evangelion",
        genres: ["Action", "Drama", "Mecha", "Psychological"],
        tags: ["Mecha", "Psychological", "Angels", "Post-Apocalyptic", "Mind Games", "Dark", "Depression", "Complex", "Giant Robots"],
        description: "Teenagers pilot giant mechs to fight mysterious beings called Angels while dealing with psychological trauma and existential questions.",
        image: "https://cdn.myanimelist.net/images/anime/10/20723.jpg",
        score: 8.5,
        episodes: 26,
        status: "Finished",
        year: 1995,
        type: "TV",
        studio: "Gainax"
    },
    {
        id: 12,
        title: "Code Geass",
        titleSecondary: "Code Geass: Lelouch of the Rebellion",
        genres: ["Drama", "Mecha", "Military", "Thriller"],
        tags: ["Mecha", "Military", "Strategy", "Supernatural Power", "Politics", "Anti-Hero", "Mind Control", "Rebellion", "War"],
        description: "A prince gains a supernatural power and leads a rebellion against his own empire using strategy, mechs, and political manipulation.",
        image: "https://cdn.myanimelist.net/images/anime/5/50331.jpg",
        score: 8.9,
        episodes: 50,
        status: "Finished",
        year: 2006,
        type: "TV",
        studio: "Sunrise"
    },
    {
        id: 13,
        title: "Mobile Suit Gundam",
        titleSecondary: "Mobile Suit Gundam",
        genres: ["Action", "Drama", "Mecha", "Military", "Space"],
        tags: ["Mecha", "Space War", "Military", "Politics", "War", "Giant Robots", "Space", "Colony", "Classic"],
        description: "In a future where humans have colonized space, a war breaks out between Earth and space colonies, fought with giant robots called mobile suits.",
        image: "https://cdn.myanimelist.net/images/anime/9/20936.jpg",
        score: 7.8,
        episodes: 43,
        status: "Finished",
        year: 1979,
        type: "TV",
        studio: "Sunrise"
    },
    {
        id: 14,
        title: "K-On!",
        titleSecondary: "K-On!",
        genres: ["Comedy", "Music", "School", "Slice of Life"],
        tags: ["Music", "School", "Friendship", "Slice of Life", "Comedy", "Band", "Moe", "Cute Girls", "Light-hearted"],
        description: "Four high school girls form a light music club and learn to play instruments while enjoying their daily school life and building friendships.",
        image: "https://cdn.myanimelist.net/images/anime/10/76121.jpg",
        score: 7.8,
        episodes: 39,
        status: "Finished",
        year: 2009,
        type: "TV",
        studio: "Kyoto Animation"
    },
    {
        id: 15,
        title: "Monster",
        titleSecondary: "Monster",
        genres: ["Drama", "Horror", "Mystery", "Psychological", "Thriller"],
        tags: ["Psychological", "Thriller", "Serial Killer", "Mind Games", "Medical", "Dark", "Mystery", "Crime", "Mature"],
        description: "A Japanese neurosurgeon becomes involved in a series of murders connected to a former patient, leading him into a psychological cat-and-mouse game.",
        image: "https://cdn.myanimelist.net/images/anime/10/18793.jpg",
        score: 9.1,
        episodes: 74,
        status: "Finished",
        year: 2004,
        type: "TV",
        studio: "Madhouse"
    },
    {
        id: 16,
        title: "Death Note",
        titleSecondary: "Death Note",
        genres: ["Drama", "Psychological", "Supernatural", "Thriller"],
        tags: ["Psychological", "Mind Games", "Death", "Supernatural", "Cat and Mouse", "Dark", "Genius", "Detective", "Thriller"],
        description: "A high school student finds a notebook that can kill anyone whose name is written in it, leading to a psychological battle with a detective.",
        image: "https://cdn.myanimelist.net/images/anime/9/9453.jpg",
        score: 8.6,
        episodes: 37,
        status: "Finished",
        year: 2006,
        type: "TV",
        studio: "Madhouse"
    },
    {
        id: 17,
        title: "Your Name",
        titleSecondary: "Kimi no Na wa",
        genres: ["Drama", "Romance", "Supernatural"],
        tags: ["Body Swap", "Romance", "Time", "Rural", "Urban", "Friendship", "Beautiful Animation", "Emotional", "Movie"],
        description: "Two teenagers share a profound, magical connection when they begin swapping bodies, leading to an extraordinary journey across space and time.",
        image: "https://cdn.myanimelist.net/images/anime/5/87048.jpg",
        score: 8.4,
        episodes: 1,
        status: "Finished",
        year: 2016,
        type: "Movie",
        studio: "CoMix Wave Films"
    },
    {
        id: 18,
        title: "Spirited Away",
        titleSecondary: "Sen to Chihiro no Kamikakushi",
        genres: ["Adventure", "Family", "Fantasy", "Supernatural"],
        tags: ["Magic", "Spirits", "Adventure", "Coming of Age", "Fantasy World", "Studio Ghibli", "Classic", "Family-Friendly"],
        description: "A young girl becomes trapped in a magical world of spirits and must work at a bathhouse to save her parents and find her way home.",
        image: "https://cdn.myanimelist.net/images/anime/6/79597.jpg",
        score: 9.3,
        episodes: 1,
        status: "Finished",
        year: 2001,
        type: "Movie",
        studio: "Studio Ghibli"
    },
    {
        id: 19,
        title: "Haikyuu!!",
        titleSecondary: "Haikyuu!!",
        genres: ["Comedy", "Drama", "School", "Sports"],
        tags: ["Volleyball", "School", "Friendship", "Tournament", "Sports", "Teamwork", "Competition", "Shonen", "Training"],
        description: "A short boy joins his high school volleyball team and aims to become a great player despite his height disadvantage.",
        image: "https://cdn.myanimelist.net/images/anime/7/76014.jpg",
        score: 8.7,
        episodes: 85,
        status: "Finished",
        year: 2014,
        type: "TV",
        studio: "Production I.G"
    },
    {
        id: 20,
        title: "One Piece",
        titleSecondary: "One Piece",
        genres: ["Action", "Adventure", "Comedy", "Drama", "Shounen"],
        tags: ["Pirates", "Adventure", "Friendship", "Powers", "Ocean", "Treasure Hunt", "Long Running", "Shonen", "Epic"],
        description: "A young pirate captain gathers a diverse crew as they sail the Grand Line in search of the ultimate treasure known as One Piece.",
        image: "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
        score: 9.0,
        episodes: 1000,
        status: "Ongoing",
        year: 1999,
        type: "TV",
        studio: "Toei Animation"
    }
];
